CREATE TABLE REL_202_SONGS_ALBUMS (
    song_id TEXT NOT NULL REFERENCES TB_004_SONGS(id) ON DELETE CASCADE,
    album_id TEXT NOT NULL REFERENCES TB_006_ALBUMS(id) ON DELETE CASCADE
);

ALTER TABLE REL_202_SONGS_ALBUMS
ADD CONSTRAINT PK_202_SONGS_ALBUMS PRIMARY KEY (song_id, album_id);

COMMENT ON TABLE REL_202_SONGS_ALBUMS IS '曲とアルバムの多対多関係';