CREATE TABLE REL_200_PLAYLISTS_SONGS(
    playlist_id TEXT NOT NULL REFERENCES TB_003_PLAYLISTS(id) ON DELETE CASCADE,
    song_id TEXT NOT NULL REFERENCES TB_004_SONGS(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    deleted_at TIMESTAMPTZ
);

ALTER TABLE REL_200_PLAYLISTS_SONGS
ADD CONSTRAINT PK_200_PLAYLISTS_SONGS PRIMARY KEY (playlist_id, song_id);

COMMENT ON TABLE REL_200_PLAYLISTS_SONGS IS 'プレイリストと曲の多対多関係';