CREATE TABLE REL_201_SONGS_ARTISTS (
    song_id TEXT NOT NULL REFERENCES TB_004_SONGS(id) ON DELETE CASCADE,
    artist_id TEXT NOT NULL REFERENCES TB_005_ARTISTS(id) ON DELETE CASCADE,
    role_code INTEGER
);

ALTER TABLE REL_201_SONGS_ARTISTS
ADD CONSTRAINT PK_201_SONGS_ARTISTS PRIMARY KEY (song_id, artist_id);

COMMENT ON TABLE REL_201_SONGS_ARTISTS IS '曲とアティストの多対多関係';