CREATE TABLE TB_007_LYRICS (
    id TEXT,
    song_id TEXT NOT NULL REFERENCES TB_004_SONGS(id) ON DELETE CASCADE,
    song_title VARCHAR(255) NOT NULL,
    lycris_url TEXT NOT NULL,
    create_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    update_at TIMESTAMPTZ,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    delete_at TIMESTAMPTZ
);

ALTER TABLE TB_007_LYRICS
ADD CONSTRAINT PK_007_LYRICS PRIMARY KEY (id);

COMMENT ON TABLE TB_007_LYRICS IS '歌詞';