CREATE TABLE TB_005_ARTISTS(
    id TEXT,
    name VARCHAR(255) NOT NULL,
    bio TEXT,
    country_code INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    deleted_at TIMESTAMPTZ
);

ALTER TABLE TB_005_ARTISTS
ADD CONSTRAINT PK_005_ARTISTS PRIMARY KEY (id);

COMMENT ON TABLE TB_005_ARTISTS IS 'アティスト';