CREATE TABLE TB_002_OTPS(
    e164_phone_num VARCHAR(30),
    otp_code VARCHAR(6),
    create_at TIMESTAMP NOT NULL,
    exp_at TIMESTAMP NOT NULL
);

ALTER TABLE TB_002_OTPS
ADD CONSTRAINT PK_002_OTPS PRIMARY KEY (e164_phone_num);

COMMENT ON TABLE TB_002_OTPS IS 'OTP検証';
