CREATE TABLE TB_003_PLAYLIST(
    id TEXT,
    name VARCHAR(100) NOT NULL,
    user_id VARCHAR(30) NOT NULL,
    description TEXT,
    cover_image VARCHAR(255),
    -- is_public BOOLEAN DEFAULT TRUE NOT NULL,
    create_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    update_at TIMESTAMPTZ DEFAULT NOW() ,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    delete_at TIMESTAMPTZ
);

ALTER TABLE TB_003_PLAYLIST
ADD CONSTRAINT PK_003_PLAYLIST PRIMARY KEY (id);

COMMENT ON TABLE TB_003_PLAYLIST IS 'プレーリスト';
