CREATE TABLE TB_003_PLAYLISTS(
    id TEXT,
    name VARCHAR(100) NOT NULL,
    user_id TEXT NOT NULL REFERENCES TB_001_USERS(id) ON DELETE CASCADE,
    is_default BOOLEAN DEFAULT FALSE NOT NULL,
    create_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    update_at TIMESTAMPTZ,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    delete_at TIMESTAMPTZ
);

ALTER TABLE TB_003_PLAYLISTS
ADD CONSTRAINT PK_003_PLAYLISTS PRIMARY KEY (id);

COMMENT ON TABLE TB_003_PLAYLISTS IS 'プレーリスト';