CREATE TABLE TB_001_USERS(
    id TEXT,
    name VARCHAR(100) NOT NULL,
    password BYTEA NOT NULL,
    e164_phone_num VARCHAR(30) UNIQUE NOT NULL,
    dial_code NUMERIC(5, 0) NOT NULL,
    national_phone_num NUMERIC(20) NOT NULL,
    country_name VARCHAR(100) NOT NULL,
    last_login_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    create_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    update_at TIMESTAMPTZ DEFAULT NOW(),
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    delete_at TIMESTAMPTZ
);

ALTER TABLE TB_001_USERS
ADD CONSTRAINT PK_001_USERS PRIMARY KEY (id);

COMMENT ON TABLE TB_001_USERS IS '利用者';